# Generated by Django 4.0.3 on 2022-03-05 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_transacao', models.CharField(blank=True, max_length=200)),
                ('valor_transacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transacao', models.DateField(default=datetime.datetime.now)),
                ('tipo_transacao', models.CharField(max_length=200)),
            ],
        ),
    ]
